config/routes.rb
Rails.application.routes.draw do
  get 'twilios/index'
  post 'twilios/create'
  post 'twilios/create_outgoing_log'

  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'twellio' => 'static_pages#twellio'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
      post :add
      post :add_user
      delete :delete_user
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :collective_inquiries

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :twilio_incoming_logs
  has_many :twilio_outgoing_logs
  has_many :tel_inquiries
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email # オブジェクトがデータベースに保存される前に処理
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_SCREEN_NAME_REGEX = /\A[\w]+\z/
  validates :screen_name, presence: true, length: {maximum: 25},
            format: {with: VALID_SCREEN_NAME_REGEX},
            uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 与えられた文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションで使用するユーザーをデータベースに記憶する(6章でいうpassword_digest)
  def remember
    self.remember_token = User.new_token
    # データベース更新でrememberカラムにトークンをハッシュ化したものを入れる
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  # def authenticated?(remember_token)
  #   return false if remember_digest.nil?
  #   BCrypt::Password.new(remember_digest).is_password?(remember_token)
  # end
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated,      true)
    update_attribute(:activated_at,   Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # 試作feedの定義
  # 完全な実装は第12章「ユーザーをフォローする」を参照してください。
  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                    OR user_id = :user_id OR reply_to_user_id = :user_id", user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # 一括
  # def tmp_save(facility_id)
  #   if session[:facility_ids].blank?
  #     p "空ですよ"
  #     session[:facility_ids] = []
  #     session[:facility_ids] << facility_id
  #     p session
  #   else
  #     p "すでにあります"
  #     session[:facility_ids] << facility_id
  #     p session
  #   end
  # end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ユーザー一覧,編集,更新,削除を行う時にはログイン済みであるかどうかを確認する
  # before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
  #                                     :following, :followers]
  # 編集,更新を行う時には正しいユーザーであるかどうかを確認する
  skip_before_action :verify_authenticity_token
  before_action :correct_user, only: [:edit, :update]
  # 削除を行うときには管理者かどうか確認する
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
    gon.users = User.all
    # @client = Twilio::REST::Client.new
    # @client.calls.list
    #   .each do |call|
    #   puts call.duration
    #   puts call.to
    # end
    # render nothing: true
    # response = Twilio::TwiML::VoiceResponse.new
    # response.dial(caller_id: '+815031886593') do |dial|
    #   dial.number('+818016015579')
    # end
    # # response.say('Hello World')
    # # response.record(action: 'https://0606224c.ngrok.io/users', method: 'POST',
    # #                 max_length: 20)
    # render xml: response.to_s
  end

  def new
    @user = User.new
    # account_sid = 'AC31921c354856a6484fedca68a8d6d9f1'
    # auth_token = 'f702269f50e15cd35225087946306c08'
    # @client = Twilio::REST::Client.new
    # @client.api.account.calls.create(
    #   from: '+815031889838',
    #   to: '+818016015579',
    #   url: users_url,
    #   method: 'GET'
    # )
    # redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  # 新規ユーザーの作成
  # 新規ユーザーの登録後,ユーザー有効化メールを送信
  def create
    p 'create'
    p params
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:success] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      # 更新に成功した時の処理
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def add
    if session[:facility_ids].blank?
      p "空ですよ"
      session[:facility_ids] = []
      session[:facility_ids] << params[:id]
      p session
    else
      p "すでにあります"
      unless session[:facility_ids].include?(params[:id])
        session[:facility_ids] << params[:id]
      end
      p session
      # session[:facility_ids] = nil
    end
    redirect_to users_url
  end

  def add_user
    if session[:users_ids].blank?
      p "空ですよ"
      session[:users_ids] = []
      session[:users_ids] << params[:id].to_i
      p session
    else
      p "すでにあります"
      unless session[:users_ids].include?(params[:id])
        session[:users_ids] << params[:id].to_i
      end
      p session
      # session[:facility_ids] = nil
    end
    # redirect_to user_path(params[:id])
    @user = User.find(params[:id])
    # ログインしていたらフォローする
    current_user.follow(@user) if logged_in?

    respond_to do |format|
      format.html { redirect_to user_path(params[:id]) }
      format.js
    end
  end

  def delete_user
    @user = User.find(params[:id])
    # ログインしていたらアンフォローする
    unfollow_user = Relationship.find_by(followed_id: params[:id]).try(:followed) if logged_in?
    current_user.unfollow(unfollow_user) if logged_in? && unfollow_user.present?
    session[:users_ids].delete(params[:id].to_i)
    respond_to do |format|
      format.html { redirect_to user_path(params[:id]) }
      format.js
    end
    # redirect_to user_path(params[:id])
  end

  # # フォロー
  # def create
  #   @user = User.find(params[:followed_id])
  #   current_user.follow(@user)
  #   respond_to do |format|
  #     format.html { redirect_to @user }
  #     format.js
  #   end
  # end
  #
  # # アンフォロー
  # def destroy
  #   @user = Relationship.find(params[:id]).followed
  #   current_user.unfollow(@user)
  #   respond_to do |format|
  #     format.html { redirect_to @user }
  #     format.js
  #   end
  # end

  private

    def user_params
      params.require(:user).permit(:name, :screen_name, :email, :password,
                                   :password_confirmation)
    end

    # beforeフィルター

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  include SessionsHelper

  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def show_follow?(session, user)
    if current_user.present?
      session.present? && session.include?(user.id) || current_user.following?(user)
    else
      session.present? && session.include?(user.id)
    end
  end

  def sum_count(session, following)
    (session.to_a + following.to_a).uniq.count
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<#% unless current_user?(@user) %>
<%= session[:users_ids] %>

<div id="follow_form">
  <% if show_follow?(session[:users_ids], @user) %>
    <%= render 'session_unfollow' %>
  <% else %>
    <%= render 'session_follow' %>
  <% end %>
</div>
<%# end %>

app/views/users/_session_follow.html.erb
<%= link_to 'follow', add_user_user_path(@user.id), remote: true, method: :post, id: 'follow', class: 'btn btn-primary' %>

app/views/users/_session_unfollow.html.erb
<%= link_to 'unfollow', delete_user_user_path(@user.id), remote: true, method: :delete, class: 'btn btn-danger' %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                    html: { method: :delete},
                    remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, add_user_path(user.id), method: :post %>
  <%= link_to "@#{user.screen_name}", user %>
  <!--管理者権限者自身は削除できない-->
  <% if current_user.try(:admin?) && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: {confirm: "You sure?"} %>
  <% end %>
</li>

app/views/users/add_user.js.erb
//フォロー用のフォームをunfollowパーシャルで更新しフォロワーのカウントを更新
$("#follow_form").html("<%= escape_javascript(render('users/session_unfollow')) %>");
$("#sessionf").html('<%= session[:users_ids].count %>');

app/views/users/delete_user.js.erb
//フォロー用のフォームをunfollowパーシャルで更新しフォロワーのカウントを更新
$("#follow_form").html("<%= escape_javascript(render('users/session_follow')) %>");
$("#sessionf").html('<%= session[:users_ids].count %>');

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :screen_name %>
        <%= f.text_field :screen_name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= session[:facility_ids] %>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :screen_name %>
        <%= f.text_field :screen_name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <span class="screen_name">
        <%= "@#{@user.screen_name}" %>
      </span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' %>
    <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
    <% end %>
  </div>
  <%= link_to image_tag("rails.png", alt: "Rails logo", class: 'picture-image'),
              'http://rubyonrails.org/', id: 'fuga', class: 'picture' %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
                <%= link_to gravatar_for(user, size: 30), user %>
            <% end %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
    <% end %>
  </div>
</div>