config/routes.rb
Rails.application.routes.draw do
  get 'twilios/index'
  post 'twilios/create'
  post 'twilios/create_outgoing_log'

  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'twellio' => 'static_pages#twellio'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
      post :add
      post :add_user
      delete :delete_user
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :collective_inquiries

end

app/controllers/collective_inquiries_controller.rb
class CollectiveInquiriesController < ApplicationController

  def index
    if logged_in?
      @users = User.where(id: (current_user.following_ids + session[:users_ids].to_a).uniq)
    else
      @users = User.where(id: session[:users_ids])
    end
  end

  def new
    p "new"
    p params[:user_ids]
    @users = User.where(id: params[:user_ids])
    p "user"
    p @users
    # if logged_in?
    #   @users = User.where(id: (current_user.following_ids + session[:users_ids].to_a).uniq)
    # else
    #   @users = User.where(id: session[:users_ids])
    # end

    @micropost = Micropost.new
  end

  def create
    count = 0
    ActiveRecord::Base.transaction do
      micropost_params[:user_id].each do |user_id|
        @micropost = Micropost.new(micropost_params)
        @micropost.user_id = user_id
        @micropost.save
        count += 1
      end
      flash[:success] = "#{count}件の問い合わせが完了しました"
      redirect_to root_url
    end
      render 'new'
    rescue => e
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture, :reply_to_user_id, user_id: [])
    end

    # def correct_user
    #   @micropost = current_user.microposts.find_by(id: params[:id])
    #   redirect_to root_url if @micropost.nil?
    # end
end

app/views/collective_inquiries/index.html.erb
<h1>一括問い合わせ</h1>

<%= form_tag new_collective_inquiry_path, method: :get do %>

  <%= check_box_tag :all, id: 'all' %>
  <%= label_tag :all, 'すべて選択' %>

  <br>

  <% @users.each do |user| %>
    <%= user.name %>
    <%= check_box_tag 'user_ids[]', user.id, false %>
  <% end %>

  <%= submit_tag "一括問い合わせする", class: "btn btn-primary" %>
<% end %>

app/views/collective_inquiries/new.html.erb
<h1>一括問い合わせ</h1>
<% if session[:users_ids].present? %>
  <%= session[:users_ids].count %>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@micropost, url: collective_inquiries_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <% @users.each do |user| %>
        <%= user.name %>
        <%= f.hidden_field :user_id, multiple: true, value: user.id %>
      <% end %>

      <%= f.submit "一括問い合わせ", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>